lanl/scico

scico/test/linop/test_linop.py, scico/test/linop/test_radon.py
* Pass rtol as in input to adjoint tests
* Use loose tolerances for radon tests on GPU
=> Set test_radon tolerances based on CPU/GPU

docs/source/conf.py
Address docs build warnings due to NEP35 cross reference in docstrings of some functions imported from `numpy`.
=> Address docs build warnings

scico/admm.py, scico/objax.py, scico/pgm.py
Minor api docs fixes in `scico.admm`.
=> Docs fixes

scico/test/test_data.py
Added individually to each method but looking to make a modularized version using either fixtures or something similar. At first glance, that idea did not seem to work, but I'll check other alternatives out.
=> Added additional information to error when data submodule is not present

scico/linop/__init__.py, scico/linop/_linop.py, scico/test/linop/test_circconv.py, scico/test/linop/test_convolve.py, scico/test/linop/test_dft.py, scico/test/linop/test_diff.py, scico/test/linop/test_linop.py, scico/test/linop/test_optics.py, scico/test/linop/test_radon_astra.py, scico/test/linop/test_radon_svmbir.py, scico/test/linop/test_stack.py, scico/util.py
Improve LinearOperator adjoint tests. Resolves #66.
=> Improve LinearOperator adjoint tests

INSTALL.rst, requirements.txt
These were the changes needed to get a GPU install of SCICO working on toro. Partially addresses #44 in that it pins the jax version but doesn't set up a build matrix to test SCICO with multiple versions of jax. Also updates instructions.
=> Pin jax version and update pip install instructions

INSTALL.rst, README.rst, docs/source/contributing.rst, docs/source/install.rst, docs/source/operator.rst, docs/source/style.rst, scico/_generic_operators.py
This PR addresses the todos in the contributing, style, and operators sections of the documentation. Makes the install a fork tutorial instead, adds references to style guides used, and creates docstrings for marked wrapper methods. 
It is still a draft waiting for some edits in the installation section.
=> Check todo in docs

scico/linop/__init__.py, scico/linop/_linop.py, scico/test/linop/test_linop.py
Add function to compute operator norm.
=> Add function to compute operator norm

docs/source/notes.rst, scico/admm.py, scico/loss.py
In relevant equations, replace `A^*` with `A^H` to denote the Hermitian conjugate.
=> Consistent notation for Hermitian conjugate

.github/workflows/pytest.yml, scico/functional/_denoiser.py, scico/functional/_flax.py, scico/test/linop/test_linop.py, scico/test/test_functional.py
Minor clean up of related code, and add tests for DnCNN.
Addresses absence of tests referred to in #84. PR will be left in draft mode until DnCNN support for RGB images is fixed, at which point the corresponding test will be enabled (currently skipped).
=> Add tests for DnCNN

scico/test/test_data.py
Skip test based on content of `scico/data/examples` rather than content of of `data` directory.
Still to be confirmed that this modified skip test still achieves the original goal of skipping the tests for `scico.data` when run within a cloned repo without the `scico-data` submodule present.
Resolves #98.
=> Skip test based on content of scico/data/examples

examples/scripts/ct_astra_weighted_tv_admm.py
Rebuilt all the examples on GPU. *Should* be warning-free, but another pair of eyes wouldn't hurt.
=> Rebuild examples

.github/workflows/lint.yml, .github/workflows/lint_optional.yml, scico/__init__.py, scico/_autograd.py, scico/_generic_operators.py, scico/blockarray.py, scico/linop/optics.py, scico/linop/radon_astra.py, scico/numpy/__init__.py, scico/numpy/linalg.py
The check is called "lint-optional" and can easily be extended to check more formatting.
closes #100
=> Add pylint check for missing docstrings

scico/linop/_linop.py
Allow specification of test vectors in `scico.linop.valid_adjoint` and clean up docstring.
Note that this PR is for a merge to `smajee/test-fix-astra`, not to `main`.
=> Allow specification of test vectors in scico.linop.valid_adjoint

scico/admm.py, scico/test/test_admm.py
- Add optional relaxation to ADMM solver.
- Simplify ADMM step implementation.
=> Add optional relaxation to ADMM solver

.github/workflows/pytest.yml
This involves some code duplication in `pytest.yml`, but it gets the job done and doesn't require me (or later maintainers) to learn much about github workflow syntax. 
Closes #80.
=> Run pytest on latest jax version

requirements.txt, scico/__init__.py, scico/blockarray.py, scico/test/linop/test_diff.py, scico/test/test_blockarray.py, scico/test/test_functional.py, scico/test/test_operator.py, scico/test/test_random.py
Mostly this involved adapting to the restructuring of `jax.xla`. But it also required:
- some reworking of `test_blockarray` because `median` was no longer happy being called on complex arrays.
- a change in `test_functional` because `[snp.isscalar(x) for x in a_1D_jax_array]` no longer returns `[True, True, ...]`. 
Tested on GPU.
Closes #127
=> Bump jax version

examples/makenotebooks.py, examples/notebooks_requirements.txt, examples/scripts/ct_astra_tv_admm.py, examples/scripts/ct_astra_weighted_tv_admm.py, examples/scripts/ct_svmbir_ppp_bm3d_admm_cg.py, examples/scripts/ct_svmbir_ppp_bm3d_admm_prox.py, examples/scripts/deconv_circ_tv_admm.py, examples/scripts/deconv_microscopy_allchn_tv_admm.py, examples/scripts/deconv_microscopy_tv_admm.py, examples/scripts/deconv_ppp_bm3d_admm.py, examples/scripts/deconv_ppp_dncnn_admm.py, examples/scripts/denoise_tv_iso_multi.py, examples/scripts/sparsecode_admm.py, examples/scripts/sparsecode_poisson_blkarr_pgm.py, examples/scripts/sparsecode_poisson_pgm.py
* Improve notebook build script
- don't terminate entire run on single notebook execution failure
- clean up workers after keyboard interrupt
* Minor edits to example script docstrings
=> Changes to examples scripts

examples/scripts/ct_astra_tv_admm.py, examples/scripts/ct_astra_weighted_tv_admm.py, examples/scripts/ct_svmbir_ppp_bm3d_admm_cg.py, examples/scripts/ct_svmbir_ppp_bm3d_admm_prox.py, examples/scripts/ct_svmbir_tv_multi.py, examples/scripts/deconv_ppp_bm3d_admm.py, examples/scripts/deconv_ppp_dncnn_admm.py, examples/scripts/demosaic_ppp_bm3d_admm.py, examples/scripts/denoise_tv_iso_admm.py, scico/optimize/admm.py, scico/test/optimize/test_admm.py
Change cg_kwargs mechanism so that default values are preserved unless explicitly changed.
Resolves #69 (but, contrary to the speculation in that issue, some of the examples seem to benefit from controlling both CG tolerance and maximum iterations).
=> Modify cg_kwargs mechanism in admm.LinearSubproblemSolver

.pre-commit-config.yaml, dev_requirements.txt, docs/source/contributing.rst
Fixes #113 
Changes proposed by this PR can be summarized as follows :-
- Adds `pylint` to `.pre-commit-config.yaml` using instructions from the official pylint documentation [here](https://pylint.pycqa.org/en/latest/user_guide/pre-commit-integration.html) with appropriate flags from the [**`lint_optional.yml`**](https://github.com/lanl/scico/blob/main/.github/workflows/lint_optional.yml) file.
- Adds `pylint` to `dev_requirements.txt`.
=> Add pylint to `pre-commit`

.pre-commit-config.yaml, CHANGES.rst, docs/source/contributing.rst, docs/source/team.rst, examples/scripts/ct_astra_tv_admm.py, examples/scripts/ct_svmbir_ppp_bm3d_admm_cg.py, examples/scripts/ct_svmbir_ppp_bm3d_admm_prox.py, examples/scripts/ct_svmbir_tv_multi.py, examples/scripts/deconv_circ_tv_admm.py, examples/scripts/deconv_microscopy_allchn_tv_admm.py, examples/scripts/deconv_microscopy_tv_admm.py, examples/scripts/deconv_ppp_bm3d_admm.py, examples/scripts/deconv_ppp_dncnn_admm.py, examples/scripts/deconv_tv_admm.py, examples/scripts/demosaic_ppp_bm3d_admm.py, examples/scripts/denoise_tv_iso_multi.py, pytest.ini, scico/__init__.py, scico/diagnostics.py, scico/optimize/_ladmm.py, scico/optimize/_primaldual.py, scico/optimize/admm.py, scico/optimize/pgm.py, scico/test/optimize/test_admm.py, scico/test/test_diagnostics.py, setup.py
- Modify `setup.py` to improve consistency in dependency specification
- Add note to docs on pinning black version in conda
- Implement more compact iteration stats initialization in optimizer classes (except PGM)
- Additional iteration stats columns for iterative ADMM subproblem solvers
- More robust implementation of `IterationStats.__init__`
- Abbreviate ADMM primal residual column name in iteration stats
- Suppress annoying pytest DeprecationWarning regarding imp in compat
=> Miscellaneous changes

scico/linop/_linop.py, scico/test/linop/test_linop.py
The part I'm least happy with is that I find the resulting (broadcasted) shape of `x * y` for two BlockArrays empirically, i.e., by multiplying zeros together. I would love an `snp.broadcast_shapes` but adding it was nontrivial.
=> Allow Diagonal to use broadcasting

scico/optimize/_ladmm.py, scico/optimize/_primaldual.py, scico/test/optimize/test_ladmm.py, scico/test/optimize/test_pdhg.py
The copy calls in the current implementations prevent solving problems using `BlockArray` variables since `copy` is not implemented for that class. The `copy` calls should not be necessary since the relevant working variables should be `DeviceArray`, and therefore immutable, due to the `ensure_on_device` calls in initializing them.
=> Remove problematic array copy operations

examples/scripts/ct_astra_tv_admm.py, examples/scripts/ct_astra_weighted_tv_admm.py, examples/scripts/ct_svmbir_ppp_bm3d_admm_cg.py, examples/scripts/ct_svmbir_ppp_bm3d_admm_prox.py, examples/scripts/deconv_circ_tv_admm.py, examples/scripts/deconv_microscopy_allchn_tv_admm.py, examples/scripts/deconv_microscopy_tv_admm.py, examples/scripts/deconv_ppp_bm3d_admm.py, examples/scripts/deconv_ppp_dncnn_admm.py, examples/scripts/deconv_tv_admm.py, examples/scripts/sparsecode_admm.py, scico/linop/_linop.py
Address some docs build warnings.
=> Address some docs build warnings

examples/scripts/ct_astra_weighted_tv_admm.py
Changes should appear at https://scico--158.org.readthedocs.build/en/158/examples/ct_astra_weighted_tv_admm.html
closes #153
=> Fix explanation of weight in weighted CT example

docs/docs_requirements.txt
As a temporary solution, pin `sphinx-autodoc-typehints` to v1.14.1. See #168.
=> Address readthedocs build failure

docs/docs_requirements.txt
=> Bump sphinx-autodoc-typehints version to avoid readthedocs build error

scico/blockarray.py, scico/loss.py, scico/numpy/__init__.py, scico/scipy/special.py, scico/typing.py
=> Address TODO in code

docs/docs_requirements.txt, docs/source/conf.py, scico/flax.py
Silence docs build warnings discussed in #167. As a side effect (the desirability of which is perhaps worthy of discussion), disables documentation of inherited methods in `scico.jax` classes. In addition, the version pinning of `sphinx-autodoc-typehints` introduced in #171 is no longer necessary (also worth discussing whether this pinning should now be removed).
=> Silence docs build warnings

docs/source/functional.rst, examples/scripts/denoise_tv_iso_pgm.py, scico/functional/_functional.py, scico/functional/_indicator.py, scico/functional/_norm.py, scico/loss.py
=> Make prox notation consistent

LICENSE, docs/source/conf.py, examples/scripts/deconv_ppp_dncnn_admm.py, scico/functional/_denoiser.py
Primary fixes:
* Redundant scaling parameter for DnCNN prox in the example.
* Missing ``**kwargs`` in signature resulted in failure when prox called without a scaling.
Also a number of other minor changes.
=> Fix some problems in DnCNN implementation and example

scico/functional/_denoiser.py, scico/linop/radon_svmbir.py
Fixes output types of svmbir and bm3d to be always jaxarrays. Fixes issue #93
=> Make output types jax-array

examples/notebooks_requirements.txt, misc/conda/install_conda.sh, misc/conda/make_conda_env.sh, requirements.txt
Update conda install scripts:
* Update `jaxlib` version
* Update `astra-toolbox` install method
* Default Python version now 3.9
* Handle additional dependencies for `svmbir` and `bm3d`
=> Update conda install scripts

.github/workflows/pytest.yml, README.rst, docs/source/overview.rst, scico/_generic_operators.py, scico/array.py, scico/blockarray.py, scico/functional/_functional.py, scico/linop/_diff.py, scico/linop/radon_svmbir.py, scico/optimize/_ladmm.py, scico/optimize/_primaldual.py, scico/optimize/pgm.py
Miscellaneous minor improvements
=> Miscellaneous minor improvements

scico/functional/_norm.py
Intended as a temporary workaround for the intermittent test failures discussed in #212 .
=> Change svd call to avoid compute_uv=False

docs/source/references.bib, scico/functional/_norm.py
A minor change to the work-around for google/jax#9483 that takes advantage of the low frequency of occurrence of the bug, and avoids potentially very high memory requirements for non-square matrices by use of the `full_matrices=False`  option.
=> Address excessive memory usage in `functional.NuclearNorm.__call__`

scico/loss.py, scico/test/test_functional.py
See #215
Note that check for `self.has_prox`, namely that `W` is `Diagonal`, was redundant and so I removed it.
=> add check for A not linop in prox

docs/source/examples.rst, examples/scripts/README.rst, examples/scripts/index.rst, examples/scripts/superres_ppp_dncnn_admm.py, scico/loss.py
=> Add new example script

examples/scripts/ct_abel_tv_admm.py, examples/scripts/ct_abel_tv_admm_tune.py, scico/examples.py, scico/test/test_examples.py
Fix some typing and docstring issues.
=> Fix some typing and docstring issues

.github/workflows/pytest_latest.yml, CHANGES.rst, README.rst, scico/__init__.py
=> Preparation for next release

scico/linop/_circconv.py, scico/test/linop/test_circconv.py
Check for blockarray inputs in `from_operator`.
=> Check for blockarray inputs in from_operator

scico/functional/_norm.py
=> Revert SVD workaround

scico/blockarray.py
Address the part of https://github.com/scici/scico/issues/315 that I think is worth fixing now. There remain uses of `np.random` in the tests.
=> Make user-facing code use scico.random instead of np.random

.readthedocs.yaml, docs/docs_requirements.txt, scico/_autograd.py, scico/ray/__init__.py
Fix readthedocs build failure, and address some other minor docs issues.
Note: the fix involved adding `ipython_genutils` as a direct dependency in ` docs_requirements.txt`, presumably required due to an error in a recent release of one of the other docs dependencies. It should be removed when this error has been corrected.
=> Fix readthedocs build failure

MANIFEST.in, docs/source/conf.py, scico/blockarray.py, scico/diagnostics.py, scico/functional/_functional.py, scico/linop/_convolve.py, scico/linop/_dft.py, scico/linop/_linop.py, scico/linop/_matrix.py, scico/linop/optics.py, scico/loss.py, scico/metric.py, scico/plot.py, scico/typing.py, scico/util.py
Minor clean up and packaging fix.
=> Minor clean up and packaging fix

scico/diagnostics.py, scico/loss.py, scico/optimize/admm.py
Fix some bugs/oversights in initialization of linear operators.
=> Fix bugs in `loss` module

requirements.txt, scico/blockarray.py, scico/test/test_blockarray.py, setup.py
Test failures were coming use of the deprecated `jax.ops.index`, appears to be functionally equivalent to `slice`. So, easy to fix.
Also needed to bump the tolerance on one blockarray test.
=> Make SCICO compatible with jax 0.3.4

CHANGES.rst, scico/functional/_functional.py, scico/solver.py, scico/test/test_functional.py
Add support for addition of functionals. The result is a functional without a prox, but that can be evaluated if both summand functionals can be evaluated.
=> Add support for addition of functionals

docs/source/conf.py, scico/linop/_linop.py, scico/linop/optics.py
Disable inclusion of inherited members in sphinx autodoc. Also address some sphinx warnings and style issues.
=> Sphinx autodoc configuration changes

misc/conda/README.rst, misc/conda/make_conda_env.sh
* Remove options for installation with GPU support
* Remove requirement that script be run from repo root directory
* Updates to restore functionality broken by recent changes in the repo
=> Update and fix conda environment construction script

docs/source/examples.rst, examples/scripts/README.rst, examples/scripts/index.rst, scico/test/linop/test_radon_svmbir.py
- Add missing bm4d notebook
- Improve svmbir tests
=> Misc bug fix

requirements.txt, scico/linop/_matrix.py, scico/loss.py, scico/solver.py, scico/test/functional/test_loss.py, scico/test/linop/test_linop.py, scico/test/test_blockarray.py, scico/test/test_operator.py
The main problem was that `x.copy()` no longer turns a `DeviceArray` into an `ndarray`. Instead, use `np.array(x)` or `x.from_device()`.
=> Make compatible with jax v0.3.5

docs/source/conf.py, scico/__init__.py, scico/_version.py, scico/optimize/admm.py, scico/test/test_version.py, setup.py
For development versions, append short git commit tag to version number to aid in identifying specific version in use.
Also, minor doc string style fixes.
=> Change development version number structure

scico/loss.py, scico/test/functional/test_loss.py
Improve algorithm, docs, and testing of the cubic equation root calculation used by `SquaredL2SquaredAbsLoss`.
=> Improve `SquaredL2SquaredAbsLoss`

examples/scripts/video_rpca_admm.py
Correct on oversight from #249, which changes the parameter name of `linop.Sum` from `sum_axis` to `axis`.
=> Fix parameter name in example script

.github/workflows/test_examples.yml, docs/source/contributing.rst, examples/README.rst, examples/scriptcheck.sh, examples/scripts/ct_abel_tv_admm.py, examples/scripts/ct_abel_tv_admm_tune.py, examples/scripts/deconv_circ_tv_admm.py, examples/scripts/deconv_microscopy_tv_admm.py, examples/scripts/deconv_ppp_bm3d_admm.py, examples/scripts/deconv_ppp_bm3d_pgm.py, examples/scripts/deconv_ppp_bm4d_admm.py, examples/scripts/deconv_ppp_dncnn_admm.py, examples/scripts/deconv_tv_admm.py, examples/scripts/deconv_tv_admm_tune.py, examples/scripts/denoise_tv_iso_multi.py, examples/scripts/denoise_tv_iso_pgm.py
Improve example checking script and add github action to run it on PRs.
=> Improve example checking script

scico/linop/__init__.py, scico/linop/_diff.py, scico/test/linop/test_diff.py
Modify the `FiniteDifference` linop, changing the interface and adding support for more useful boundary handling options.
=> Modify `FiniteDifference` linop

examples/makenotebooks.py, examples/scripts/deconv_tv_admm.py
Improve notebook build script and update built notebooks in submodule.
=> Improve notebook build script

scico/__init__.py, scico/_python37.py, scico/_version.py, scico/numpy/util.py, setup.py
Three main changes:
- add `math.prod` if it doesn't exist
- add `typing.Literal` if it doesn't exist
- change syntax of `parse` call in `_version.py` if it fails
=> Add Python 3.7 compatibility

misc/pytest/pytest_time.sh, scico/test/test_random.py
Improve script and resolve context-dependent test failure.
=> Improve script and resolve context-dependent test failure

CHANGES.rst, scico/linop/_dft.py, scico/linop/optics.py, scico/test/linop/test_dft.py
Extend interface of `linop.DFT`. Resolves #298.
=> Extend interface of `linop.DFT`

scico/functional/_norm.py, scico/test/functional/test_misc.py
Extend `functional.L21Norm` to support multiple l2 axes. Resolves #310.
=> Extend L21Norm to support multiple l2 axes

CHANGES.rst, scico/linop/__init__.py, scico/linop/_diff.py, scico/linop/_stack.py, scico/test/linop/test_stack.py
Looking for feedback: is the name appropriate? We have`BlockDiagonalLinearOperator` and `LinearOperatorStack`, which don't seem parallel and have the awkward "LinearOperator" part.
closes #311
=> Add block diagonal linear operator

scico/test/linop/test_linop.py
Addresses the half of #276 that I could reproduce.
=> Bump test tolerance

CHANGES.rst, requirements.txt, scico/_autograd.py, scico/linop/radon_astra.py, scico/numpy/_blockarray.py, scico/test/linop/test_radon_astra.py
Also bump jax and jaxlib version in requirements.txt.
Closes #317
=> Make compatible with jax 0.3.15

CHANGES.rst, docs/source/examples.rst, docs/source/references.bib, examples/scripts/README.rst, examples/scripts/denoise_cplx_tv_pdhg.py, examples/scripts/denoise_l1tv_admm.py, examples/scripts/denoise_tv_admm.py, examples/scripts/index.rst, scico/_generic_operators.py, scico/examples.py, scico/linop/_linop.py, scico/operator/__init__.py, scico/operator/_func.py, scico/optimize/_primaldual.py, scico/test/optimize/test_pdhg.py, scico/test/test_examples.py, scico/test/test_operator.py
Add PDHG solver with support for non-linear operators.
=> Add PDHG solver with support for non-linear operators

scico/optimize/_admm.py, scico/optimize/_ladmm.py, scico/optimize/_primaldual.py
Minor improvements to `scico.optimize` docs.
=> Minor improvements to `scico.optimize` docs

.github/workflows/pytest.yml, CHANGES.rst, docs/source/exampledepend.rst, examples/examples_requirements.txt, requirements.txt, scico/denoiser.py
=> Mitigate impact of #342

misc/conda/make_conda_env.sh, scico/test/linop/test_radon_svmbir.py
Fix conda script and work around #344.
=> Fix conda script and work around #344

docs/source/contributing.rst
=> Resolve #152

scico/optimize/_admm.py, scico/optimize/_common.py, scico/optimize/_ladmm.py, scico/optimize/_pgm.py, scico/optimize/_primaldual.py
=> Resolve issue #291

scico/solver.py, scico/test/test_solver.py
=> Resolve issue #240

scico/functional/_indicator.py
Make class docstrings agree with prox docstrings
=> Indicator documentation notation

scico/__init__.py, setup.py
Remove `jaxlib`/`jax` version tests in `scico/__init__.py`.
=> Remove `jaxlib`/`jax` version tests in `scico/__init__.py`

README.rst, docs/source/overview.rst, docs/source/references.bib
=> Add references to JOSS paper

docs/source/conf.py, requirements.txt
Fix support for building docs offline, allowing use of `sphinx.ext.imgmath` extension for equations, or specification of a local MathJax path for use with `sphinx.ext.mathjax`.
Also bump supported jaxlib/jax versions.
=> Fix support for building docs offline

docs/source/include/blockarray.rst, docs/source/notes.rst, scico/linop/_convolve.py, scico/linop/_linop.py, scico/linop/_matrix.py, scico/numpy/_wrappers.py, scico/numpy/util.py, scico/operator/_operator.py, scico/test/linop/test_convolve.py, scico/test/linop/test_matrix.py, scico/test/test_array.py
* `isinstance(x, DeviceArray)` needed to be changed to `isinstance(x, jnp.ndarray)`, which returns `True` for all kinds of jax arrays, including abstract ones, which I think is what we usually want. For more info, see https://github.com/google/jax/issues/2115.
* Needed to change the `BlockArray` function wrapping because it could not handle positional-only arguments.
* NOT fully addressed: jax has changed from `DeviceArray` to `Array` as its default array type, see https://github.com/google/jax/blob/39b14b1b1fc021ec45e431bebd53ac19a9111789/CHANGELOG.md. Probably much of our documentation talks about `DeviceArray`s still.
=> Make compatible with jax_0.4.1

scico/optimize/_common.py, scico/test/optimize/test_admm.py
Optimiser class `__init__` methods currently just ignore unrecognized keyword arguments. This PR adds such checking to avoid user confusion etc. when there is a typo in an argument name , which could lead to unexpected behaviour.
=> Add checking for unrecognized keyword arguments

examples/scripts/deconv_tv_admm.py, scico/optimize/_padmm.py
Firstly, thanks for the great package!
Just a few typos I spotted in the docs, hope you don't mind such tiny PRs
=> Fix a few typos in docstrings and an example

docs/docs_requirements.txt, docs/source/conf.py
=> Add ipython extensions and requirements to fix #397

scico/linop/_linop.py, scico/linop/radon_astra.py, scico/test/linop/test_radon_astra.py, scico/test/linop/test_radon_svmbir.py
Previously, when a LinOp needed _either_  a gram operator _or_ an adjoint, both would be automatically generated. In particular, this meant that user-defined adjoint would be overwritten if the user did not also set the gram. This PR splits the two.
Addresses #331
=> Make adjoint and gram get auto set separately 

docs/source/_templates/breadcrumbs.html, docs/source/conf.py
Remove Edit on Github button, which re-appeared in switch to `furo` theme.
=> Remove Edit on Github button (again)

docs/source/examples.rst, examples/scripts/README.rst, examples/scripts/ct_projector_comparison.py, examples/scripts/ct_projector_timing.py, examples/scripts/index.rst, scico/linop/__init__.py, scico/linop/_xray.py, scico/test/linop/test_xray.py, scico/test/test_ray_tune.py, scico/util.py
For now, it's the simplest (2D, not very configurable) example. Extension to 3D slice-by-slice should be straightforward.
The structure of the code requires input. I designed this so that the projector could easily be cut and pasted outside of SCICO if desired.
Timing versus ASTRA is encouraging, see `ct_projector_comparison.py`.
=> Add a jax-based X-ray projector

.github/workflows/pytest_ubuntu.yml, examples/examples_requirements.txt, requirements.txt
Move `bm3d` and `bm4d` to examples requirements.
=> Make bm3d and bm4d optional

CHANGES.rst, requirements.txt, scico/linop/_matrix.py, scico/numpy/util.py, scico/optimize/_admmaux.py, scico/solver.py, scico/test/linop/test_matrix.py, scico/test/test_solver.py
Rename linear problem solver and add parameter type checking.
=> Rename linear problem solver and add parameter type checking

scico/flax/train/input_pipeline.py, scico/flax/train/state.py, scico/flax/train/steps.py, scico/flax/train/trainer.py
Address `DeprecationWarning: jax.random.KeyArray is deprecated.`
=> Address deprecation warning in `scico.flax` 

docs/source/examples.rst, examples/scripts/README.rst, examples/scripts/ct_astra_tv_admm.py, examples/scripts/ct_multi_cs_tv_admm.py, examples/scripts/ct_multi_tv_admm.py, examples/scripts/ct_tv_admm.py, examples/scripts/index.rst, requirements.txt
Clean up some example scripts and rerun some notebooks. Also bump max jaxlib/jax versions.
=> Clean up some example scripts and rerun some notebooks

scico/functional/_norm.py, scico/test/functional/test_misc.py
Resolve obstacles to jitting of some functionals and add corresponding tests.
=> Resolve obstacles to jitting of some functionals

CHANGES.rst, scico/functional/_functional.py, scico/loss.py, scico/test/functional/test_loss.py, scico/test/functional/test_misc.py
Resolve #468.
Also:
* Improve scaling of `ScaledFunctional`, so that e.g. ` 5.0 * (2.0 * functional.L2Norm())` is a `ScaledFunctional` with a scale of 10 of an `L2Norm` rather than a `ScaledFunctional` with a scale of 5 of a `ScaledFunctional`.
* Some cleaning up and code re-organization.
* Update change summary `CHANGES.rst`.
=> Resolve #468

scico/linop/_circconv.py, scico/test/linop/test_circconv.py
Using a fractional filter center for a `CircularConvolve` operator currently gives nonsense results. This PR adds a test for this nonsense (checking that the imaginary part of the result of filtering is small) and changes the way centers are handled to fix the problem. Relevant references:
F. Candocia and J. C. Principe, "Comments on "Sinc interpolation of discrete periodic signals," in IEEE Transactions on Signal Processing, vol. 46, no. 7, pp. 2044-2047, July 1998, doi: 10.1109/78.700979.
"S. -C. Pei and Y. -C. Lai, "Closed Form Variable Fractional Time Delay Using FFT," in IEEE Signal Processing Letters, vol. 19, no. 5, pp. 299-302, May 2012, doi: 10.1109/LSP.2012.2191280.
=> Fix fractional centers in CircularConvolve

examples/scripts/ct_projector_comparison.py, scico/linop/xray/_xray.py, scico/test/linop/xray/test_xray.py
Reimplement the X-ray projector to avoid aliasing artifacts. This projector is on par with ASTRA in terms of speed on the GPU.
=> Update the SCICO x-ray projector

scico/linop/_stack.py, scico/operator/_stack.py, scico/test/linop/test_diff.py, scico/test/linop/test_linop_stack.py, scico/test/operator/test_op_stack.py
Resolve #479.
The solution is to simply remove the `VerticalStack`-specific arithmetic operator definitions, the need for which is unclear.
=> Resolve #479

scico/linop/_func.py, scico/operator/_func.py, scico/operator/_operator.py, scico/test/linop/test_func.py, scico/test/operator/test_operator.py
Resolve #478.
This issue has some relevance to #234 and #350. Should the additional optional parameters added in this PR be supported? If not, they shoud be removed elsewhere as well for consistency.
=> Resolve #478

scico/numpy/__init__.py, scico/numpy/_wrappers.py, scico/test/test_blockarray.py
=> Resolve #483

CHANGES.rst, examples/scriptcheck.sh, scico/__init__.py, scico/linop/xray/_xray.py
=> Release 0.0.5

.github/workflows/pytest_macos.yml, .github/workflows/pytest_ubuntu.yml, dev_requirements.txt, examples/examples_requirements.txt, requirements.txt, scico/flax/train/checkpoints.py, setup.py
Resolve some packaging issues.
=> Resolve some packaging issues

.readthedocs.yaml, docs/docs_requirements.txt, docs/rtd_requirements.txt, docs/source/conf.py
=> Fix readthedocs build

scico/numpy/_wrappers.py, scico/test/numpy/test_numpy.py
=> Correctly check for nested tuple in map_func_over_tuple_of_tuples

scico/linop/__init__.py, scico/linop/_circconv.py, scico/linop/_convolve.py, scico/linop/_diag.py, scico/linop/_linop.py, scico/linop/_matrix.py, scico/numpy/_blockarray.py, scico/numpy/_wrappers.py, scico/operator/_operator.py, scico/solver.py, scico/test/linop/test_binop.py, scico/test/linop/test_diag.py
Reduce memory requirements of `Identity` linop, and other improvements.
=> Reduce memory requirements of `Identity` linop

scico/functional/_norm.py, scico/test/functional/test_misc.py, scico/test/functional/test_norm.py
Fix `L21Norm` handling of `BlockArray` input, which currently results in multi-valued output in evaluation of the norm.
=> Fix `L21Norm` handling of `BlockArray` input

scico/numpy/util.py, scico/test/linop/test_func.py, scico/test/numpy/test_numpy_util.py
Add support for `np.newaxis` to indexing syntax supported by `linop.Slice`.
=> Add support for `np.newaxis` to indexing syntax supported by `linop.Slice`

scico/_autograd.py, scico/flax/examples/data_generation.py, scico/flax/train/traversals.py
Resolve some deprecation warnings.
=> Resolve some deprecation warnings

docs/source/_templates/autosummary/module.rst
Move Sphinx API submodule table to top of module summary. Resolves #524.
=> Move Sphinx API submodule table to top of module summary

scico/numpy/util.py, scico/test/numpy/test_numpy_util.py
This is a replacement for #519, adopting the new  version of `indexed_shape` as an alternative rather than a replacement.
=> Alternative version of `indexed_shape` with a different name

CHANGES.rst, scico/functional/_tvnorm.py, scico/linop/__init__.py, scico/linop/_diff.py, scico/linop/_stack.py, scico/numpy/util.py, scico/test/functional/test_tvnorm.py, scico/test/numpy/test_numpy_util.py, scico/typing.py
Improve the implementation of `scico.functional.TVNorm`, recucing memory requirements and computation time.
A number of other minor changes are also included in this PR.
=> Improve `TVNorm` implementation

docs/source/conf/20-extensions.py, scico/linop/xray/__init__.py, scico/numpy/util.py
Improve docs for `linop.xray` subpackage. See also lanl/scico-data#49.
The effects of the changes in the built docs may be viewed [here](https://scico--533.org.readthedocs.build/en/533/_autosummary/scico.linop.xray.html#module-scico.linop.xray). These docs are likely to be moved or edited as part of the completion of #529.
=> Improve docs for `linop.xray` subpackage

scico/linop/__init__.py, scico/linop/_stack.py, scico/operator/__init__.py, scico/operator/_stack.py, scico/test/linop/test_linop_stack.py, scico/test/operator/test_op_stack.py
Add diagonal operator mapping base operator over an array axis via `jax.pmap` or `jax.vmap`.
Resolves #413.
=> Add diagonal operator mapping base operator over an array axis

examples/scripts/ct_multi_cs_tv_admm.py, scico/linop/xray/_xray.py, scico/test/linop/xray/test_xray.py
=> Fix 2D X-ray projector bugs

scico/__init__.py, scico/test/linop/xray/test_astra.py
Fix bug in tests and avoid variability in numerical precision across devices (see google/jax#19444).
=> Fix bug in tests and avoid variability in numerical precision across devices

CHANGES.rst, requirements.txt
Bump maximum supported jax version to 0.4.31.
=> Bump maximum supported jax version to 0.4.31

examples/scripts/ct_projector_comparison_3d.py, scico/linop/xray/__init__.py, scico/linop/xray/astra.py, scico/test/linop/xray/test_astra.py
Changes to `linop.xray.astra` module:
* Add missing typing
* Fix some docstrings
* Change interface of `convert_to_scico_geometry`
Note:
* Typing still needs some attention. In particular, it's not always clear whether `jax` or `numpy` arrays should be specified, and `jax.ArrayLike` should perhaps be replaced by `numpy.typing.ArrayLike`.
* Some functions do not have any docstrings.
=> Changes to `linop.xray.astra` module

scico/linop/xray/_xray.py
Add caveat on 3D X-ray projector.
=> Add caveat on 3D X-ray projector

docs/source/conf/60-rtd.py
Transition to [Read the Docs Addons](https://about.readthedocs.com/blog/2024/07/addons-by-default/#how-to-opt-in-to-addons-now).
=> Transition to Read the Docs Addons

.github/workflows/pytest_ubuntu.yml, docs/source/install.rst, examples/scripts/ct_astra_modl_train_foam2.py, examples/scripts/ct_astra_odp_train_foam2.py, examples/scripts/ct_astra_unet_train_foam2.py, examples/scripts/deconv_modl_train_foam1.py, examples/scripts/deconv_odp_train_foam1.py, examples/scripts/denoise_dncnn_train_bsds.py, requirements.txt, scico/flax/examples/data_generation.py, scico/flax/train/checkpoints.py, scico/functional/_denoiser.py, scico/numpy/_blockarray.py, scico/numpy/_wrapped_function_lists.py
Changes required to support `jax` version 0.4.33, switch to using the new `orbax-checkpoint`  `CheckpointManager` API, and various other improvements.
=> Changes required to support `jax` version 0.4.33

scico/linop/xray/_xray.py, scico/test/linop/xray/test_xray.py
resolves #542
hypothesized to resolve a warning about dtypes from the tests
=> Fix `XRayTransform2D` projection dtype and docs

CHANGES.rst, docs/source/references.bib, scico/linop/xray/_xray.py, scico/test/linop/xray/test_xray.py
Add filtered back projection for 2D projector.
=> Add filtered back projection for 2D projector

CHANGES.rst, MANIFEST.in, README.md, examples/scripts/ct_astra_3d_tv_padmm.py, requirements.txt, scico/__init__.py, scico/linop/xray/astra.py
=> Changes for release 0.0.6

scico/linop/xray/astra.py
=> Resolve #564

.github/workflows/check_files.yml, .github/workflows/pytest_ubuntu.yml, scico/linop/xray/astra.py, scico/test/linop/test_convolve.py, scico/test/linop/xray/test_astra.py, scico/test/linop/xray/test_svmbir.py
Restore running of astra tests, and add some tests for `linop.Convolve`.
=> Restore running of astra tests

.github/workflows/pytest_macos.yml, .github/workflows/pytest_ubuntu.yml, examples/examples_requirements.txt
Remove temporary changes from pytest runs in CI.
=> Remove temporary changes from pytest runs in CI

CHANGES.rst, requirements.txt
Bump `jax` and `flax` version upper bounds. Resolves #571.
=> Bump `jax` and `flax` version upper bounds

CHANGES.rst, LICENSE, README.md, docs/source/conf/10-project.py, requirements.txt, scico/linop/xray/__init__.py, scico/linop/xray/_util.py, scico/test/linop/test_linop.py, scico/test/linop/xray/test_astra.py, scico/test/linop/xray/test_xray_util.py
Add a utility function for rotating CT volumes. Also bump maximum jaxlib/jax version to 0.5.0.
=> Add a utility function for rotating CT volumes

CHANGES.rst, examples/scripts/ct_abel_tv_admm_tune.py, examples/scripts/deconv_tv_admm_tune.py, scico/functional/__init__.py, scico/functional/_functional.py, scico/test/functional/test_composed.py, scico/test/functional/test_core.py, scico/test/functional/test_misc.py, scico/test/functional/test_separable.py, scico/test/test_denoiser.py
Add `ComposedFunctional` class representing a functional composed with an orthogonal linear operator, as well as some other minor edits.
=> Add `ComposedFunctional` class

scico/linop/xray/astra.py
Addresses #576. Is there a better place to put the text about world coordinates?
=> Improve X-ray docs

CHANGES.rst, requirements.txt, scico/random.py
Fix bug resulting from introduction of new keyword-only parameter for `jax.random` functions.
=> Resolve failure with `jax` 0.6.0

examples/scripts/denoise_ptv_pdhg.py, scico/linop/_grad.py, scico/numpy/__init__.py, scico/numpy/_blockarray.py, scico/numpy/util.py, scico/operator/_stack.py, scico/test/linop/test_grad.py, scico/test/numpy/test_blockarray.py, scico/test/numpy/test_numpy_util.py
* Modify non-Cartesian coordinate gradient operators to output `Array` instead of `BlockArray`.
* Add `stack` method to `BlockArray`
=> Changes to `BlockArray` and gradient operators

CHANGES.rst, requirements.txt
Bump `jaxlib`, `jax`, and `flax` version upper bounds.
=> Bump `jaxlib`, `jax`, and `flax` version upper bounds
