- scico/functional/_indicator.py
- scico/functional/_norm.py
- scico/linop/radon_svmbir.py
- scico/loss.py
- scico/solver.py
- scico/test/linop/test_radon_svmbir.py
- scico/test/test_functional.py
- scico/test/test_solver.py
Includes the code and tests, but currently no example.
Closes #2.
> Add new loss with prox computed by `svmbir.recon`

- scico/test/test_functional.py
> Add deterministic flag for DnCnn GPU-based tests

- examples/examples_requirements.txt
- examples/scripts/deconv_microscopy_allchn_tv_admm.py
Needed in 
https://github.com/lanl/scico/blob/4395463890ad4f28416e59c1b88831f00826cded/examples/scripts/deconv_microscopy_allchn_tv_admm.py#L43-L46
> Add missing requirement

- README.rst
Add codefactor badge to README.
> Add codefactor badge

- .github/workflows/pytest.yml
- docs/source/conf.py
- examples/examples_requirements.txt
- examples/scripts/deconv_microscopy_allchn_tv_admm.py
- examples/scripts/deconv_tv_admm_tune.py
- scico/ray/__init__.py
- scico/ray/tune.py
- scico/test/test_ray_tune.py
Add ray.tune interface and example script.
> Add ray.tune interface and example script

- scico/linop/radon_svmbir.py
- scico/test/linop/test_radon_astra.py
- scico/test/linop/test_radon_svmbir.py
> add center_offset to svmbir interface

- scico/numpy/_util.py
> Correct __module__ for wrapped functions

- .github/workflows/pytest_latest.yml
Split pytest and pytest-latest so the badge in the readme can reflect pytest only
> Split pytest and pytest-latest

- docs/source/style.rst
- scico/optimize/admm.py
- scico/optimize/pgm.py
> fix type annotations in pgm

- CHANGES.rst
- docs/source/install.rst
- scico/__init__.py
Final changes for 0.0.2 release.
> Final changes for 0.0.2 release.

- README.rst
- docs/source/conf.py
- docs/source/exampledepend.rst
- docs/source/examples.rst
- docs/source/install.rst
- docs/source/references.bib
- examples/scripts/README.rst
- examples/scripts/denoise_l1tv_iso_admm.py
- examples/scripts/denoise_tv_iso_admm.py
- examples/scripts/denoise_tv_iso_multi.py
- examples/scripts/denoise_tv_iso_pgm.py
- examples/scripts/index.rst
- scico/examples.py
- scico/functional/_functional.py
- scico/linop/radon_svmbir.py
- scico/loss.py
- scico/test/linop/test_radon_svmbir.py
- scico/test/prox.py
- scico/test/test_examples.py
- scico/test/test_functional.py
- scico/test/test_loss.py
* Add new example demonstrating ℓ1-TV denoising
* Add support for generic loss function
* Fix handling of `scale` parameter in `SVMBIRExtendedLoss.__init__`
* Clean up loss tests
* Resolve docs build warning
* Address some style violations in `radon_svmbir`
> Miscellaneous changes

- examples/scripts/ct_svmbir_ppp_bm3d_admm_prox.py
- scico/linop/radon_svmbir.py
- Fixes bug in scico.svmbir that caused errors with the new release of svmbir
- Fixes issue #198 by adding an example that uses the svmbir extended losss
> Fix bug and add example

- .readthedocs.yaml
Address missing examples in docs.
> Address missing examples in docs

- scico/linop/optics.py
> Minor docs fix

- scico/numpy/util.py
> Improve docs

- .github/workflows/pytest_latest.yml
- requirements.txt
- scico/data/__init__.py
- scico/examples.py
- scico/test/test_examples.py
Bump maximum `jaxlib`/`jax` version and address `imageio` warnings
> Bump maximum `jax` version and address `imageio` warnings

- CHANGES.rst
> Update change summary

- README.rst
- docs/docs_requirements.txt
- docs/source/conf.py
Add google colab badge to main project README file.
> Add google colab badge

- docs/source/conf.py
- docs/source/style.rst
- scico/functional/_functional.py
- scico/functional/_indicator.py
- scico/functional/_norm.py
- scico/linop/_circconv.py
- scico/test/functional/test_core.py
Add separable Huber norm and minor docs improvements.
> Add separable Huber norm and minor docs improvements.

- docs/source/contributing.rst
The previous command generated a deluge of errors. The suggested mypy command comes from the github workflow and seems more useful.
> Update type checking command

- scico/operator/_operator.py
> Address #335

- requirements.txt
- scico/operator/_operator.py
- scico/test/linop/test_func.py
Bump maximum jax version and some other small changes.
> Bump maximum jax version and some other small changes

- scico/denoiser.py
- scico/functional/_denoiser.py
- scico/linop/radon_astra.py
- scico/linop/radon_svmbir.py
> Address #324

- scico/_flax.py
- scico/denoiser.py
- scico/diagnostics.py
- scico/examples.py
- scico/functional/_functional.py
- scico/linop/_circconv.py
- scico/linop/_convolve.py
- scico/linop/_dft.py
- scico/linop/_diag.py
- scico/linop/_linop.py
- scico/linop/_matrix.py
- scico/linop/_stack.py
- scico/linop/optics.py
- scico/linop/radon_astra.py
- scico/linop/radon_svmbir.py
- scico/loss.py
- scico/numpy/_blockarray.py
- scico/numpy/_wrappers.py
- scico/numpy/util.py
- scico/operator/_operator.py
- scico/operator/biconvolve.py
- scico/optimize/_admm.py
- scico/optimize/_admmaux.py
- scico/optimize/_ladmm.py
- scico/optimize/_pgm.py
- scico/plot.py
- scico/random.py
- scico/solver.py
- scico/util.py
> Resolve #283

- scico/linop/_matrix.py
- scico/test/linop/test_matrix.py
> Resolve issue #356

- .github/workflows/pytest.yml
- .github/workflows/test_examples.yml
- requirements.txt
- scico/data/__init__.py
- scico/examples.py
- scico/numpy/_wrapped_function_lists.py
- scico/numpy/_wrappers.py
- scico/optimize/_pgmaux.py
- scico/test/functional/test_denoiser_func.py
- scico/test/test_denoiser.py
Remove deprecated numpy function and bump jaxlib/jax versions. Resolves #363.
> Remove deprecated numpy function and bump jaxlib/jax versions

- scico/denoiser.py
- scico/linop/_circconv.py
- scico/linop/_linop.py
- scico/operator/_operator.py
> Minor docstring fixes

- scico/denoiser.py
- scico/functional/_denoiser.py
- scico/test/functional/test_denoiser_func.py
Resolve bm3d/bm4d denoiser test failures.
> Resolve test failures

- docs/source/advantages.rst
- docs/source/contributing.rst
- docs/source/install.rst
- docs/source/inverse.rst
- docs/source/notes.rst
- docs/source/overview.rst
- docs/source/style.rst
Fix minor docs source file formatting issues, and correct some outdated assertions.
> Clean up docs source files

- docs/source/style.rst
- examples/makeindex.py
- scico/ray/__init__.py
> Miscellaneous docs fixes

- README.rst
- scico/flax/examples/examples.py
- scico/flax/train/clu_utils.py
- scico/flax/train/trainer.py
- scico/optimize/_common.py
- scico/test/flax/test_examples_flax.py
Resolve some typing errors and some other minor changes.
> Resolve some typing errors

- README.rst
Fix unit test status badge and link.
> Fix unit test status badge and link

- requirements.txt
> Bump max jax version

- CHANGES.rst
- scico/__init__.py
> Changes for release 0.0.4

- CHANGES.rst
- scico/__init__.py
Prepare for development of version 0.0.5.
> Prepare for development of version 0.0.5

- requirements.txt
Bump maximum `jaxlib`/`jax` versions.
> Bump maximum `jaxlib`/`jax` versions

- CHANGES.rst
- requirements.txt
Bump maximum supported jaxlib/jax version.
> Bump maximum supported jaxlib/jax version

- CHANGES.rst
- scico/__init__.py
Post-release preparation for next release.
> Post-release preparation for next release

- scico/_version.py
- setup.py
> Resolve packaging error

- docs/source/include/examplenotes.rst
- docs/source/notes.rst
- misc/availgpu.py
- scico/flax/examples/data_generation.py
- scico/linop/xray/astra.py
- scico/optimize/_ladmm.py
- scico/optimize/_padmm.py
- scico/test/linop/xray/test_astra.py
Improve GPU handling in `linop.xray.astra`, and various other minor changes.
> Improve GPU handling in `linop.xray.astra`

- scico/optimize/_padmm.py
Fixed a minor documentation mistake for the update step  in the Proximal ADMM algorithm.
> Fixed minor documentation mistake

- requirements.txt
- scico/ray/tune.py
> Resolve dependency problems

- .github/workflows/lint.yml
- .github/workflows/pytest_macos.yml
- dev_requirements.txt
- docs/source/conf/25-napoleon.py
- examples/scripts/sparsecode_poisson_apgm.py
- scico/flax/inverse.py
- scico/functional/_norm.py
- scico/linop/xray/astra.py
- scico/numpy/_blockarray.py
- scico/optimize/_admmaux.py
- scico/test/flax/test_clu.py
- scico/test/linop/test_conversions.py
Update `black` version requirement and apply latest version to source.
> Update `black` version requirement and apply latest version to source

- conftest.py
- requirements.txt
- scico/linop/xray/astra.py
Bump jaxlib/jax and flax max versions.
> Bump jaxlib/jax and flax max versions

- scico/linop/xray/astra.py
Fix minor error in `linop.xray.astra` docs.
> Fix minor error in `linop.xray.astra` docs

- docs/source/include/blockarray.rst
- docs/source/include/operator.rst
- docs/source/references.bib
> Minor docs fixes

- scico/solver.py
> Fix typo in docs

- CHANGES.rst
- requirements.txt
- scico/linop/_grad.py
- scico/solver.py
- scico/trace.py
> Bump maximum `jax` version

- CHANGES.rst
- requirements.txt
- scico/flax/examples/data_generation.py
Bump maximum `jax` and `flax` versions. Also address a typing error.
> Bump maximum `jax` and `flax` versions

- CHANGES.rst
- examples/scripts/dgm_train_S.py
- examples/scripts/dgm_train_foam2.py
- requirements.txt
- scico/flax/autoencoders/blocks.py
- scico/flax/autoencoders/steps.py
- scico/flax/autoencoders/uvarautoencoders.py
- scico/flax/autoencoders/varautoencoders.py
- scico/flax/diffusion/blocks.py
- scico/flax/diffusion/models.py
- scico/flax/diffusion/state.py
- scico/flax/diffusion/steps.py
- scico/flax/examples/data_generation.py
- scico/flax/train/losses.py
- scico/flax/train/trainer.py
- scico/linop/_grad.py
- scico/solver.py
- scico/trace.py
Fix a typo in a loss name and some typing errors.
> Minor fixes

- docs/source/conf/81-scico_scipy.py
Fix for possibly missing `scico.scipy.special.sph_harm`.
> Fix for possibly missing `scico.scipy.special.sph_harm`

- CHANGES.rst
- requirements.txt
Bump jax and flax max versions.
> Bump jax and flax max versions

- CHANGES.rst
- requirements.txt
> Bump jax and flax versions.

- docs/source/references.bib
- docs/tikxfigures/img_align.tex
- docs/tikxfigures/makesvg.sh
- docs/tikxfigures/vol_align_xyz.tex
- docs/tikxfigures/vol_align_xz.tex
- docs/tikxfigures/vol_align_yz.tex
- pyproject.toml
- scico/linop/xray/__init__.py
- scico/linop/xray/_util.py
- scico/test/linop/xray/test_xray_util.py
Add some utility functions for CT reconstruction.
> Add some utility functions for CT reconstruction.

- .github/workflows/pytest_macos.yml
- .github/workflows/pytest_ubuntu.yml
- CHANGES.rst
- examples/examples_requirements.txt
- requirements.txt
- scico/flax/train/checkpoints.py
- scico/test/flax/test_apply.py
- scico/test/flax/test_checkpoints.py
Make `orbax-checkpoint` optional.
> Make `orbax-checkpoint` optional

- scico/util.py
Resolve deprecation warning (```DeprecationWarning: jax.interpreters.batching.BatchTracer is deprecated.```)
> Resolve deprecation warning

- CHANGES.rst
Add note to change log on recent changes.
> Add note to change log on recent changes
